version: '3.0'

services:

  antispam-bot:
    build: ./
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SomePassword1997
      POSTGRES_DB: antispambot
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
