spring:
  application:
    name: antispam-bot

  datasource:
    url: jdbc:postgresql://147.45.237.196:5432/antispambot
    username: postgres
    password: SomePassword1997
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: Postgres

  sql:
    init:
      mode: always

telegram:
  bot:
    username: "for_command_test_demo_bot_bot"
    token: "6301409920:AAGgdMIdCDAHaUipawyLVgVKj0nD3Ie_dAQ"
    session:
      enable: true
      time-life:
        chat: 60
        user: 10

program-agent:
  charts:
    bot-message: true
  client:
    token: "${program_agent_client_token}"
    time-delay-send: 15000
    host: "https://wds-program-agent.ru/api/"
    myHost: "${program_agent_client_my_host}"

bot_owner_tg_id: 260113861