spring:
  application:
    name: antispam-bot

  datasource:
    url: jdbc:postgresql://postgres:5433/antispambot
    username: postgres
    password: SomePassword1997
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create

  jooq:
    sql-dialect: Postgres

telegram:
  bot:
    username: "for_command_test_demo_bot_bot"
    token: "6301409920:AAGgdMIdCDAHaUipawyLVgVKj0nD3Ie_dAQ"
    session:
      enable: true
      time-life:
        chat: 60
        user: 10

program-agent:
  charts:
    bot-message: true
  client:
    token: "34b009a9-7dc0-46f8-a4fb-f3b141bcc2b9"
    time-delay-send: 15000
    host: "https://wds-program-agent.ru/api/"
    myHost: "http://10.9.0.5:1016/api/"