spring:
  application:
    name: antispam-bot

  datasource:
    url: jdbc:postgresql://localhost:5432/antispambot
    username: postgres
    password: SomePassword1997
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: Postgres

  sql:
    init:
      mode: always

telegram:
  bot:
    username: "for_command_test_demo_bot_bot"
    token: "6301409920:AAECCXZUpqcjRzdxDscPhaV-AFIRxJHT7ow"
    session:
      enable: true
      time-life:
        chat: 60
        user: 10

program-agent:
  charts:
    bot-message: true
  client:
    token: ""
    time-delay-send: 15000
    host: "https://wds-program-agent.ru/api/"
    myHost: ""

bot_owner_tg_id: 260113861