spring:
  application:
    name: antispam-bot

  datasource:
    url: jdbc:postgresql://${datasource_url}/${datasource_database_name}
    username: ${datasource_username}
    password: ${datasource_password}
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: Postgres

  sql:
    init:
      mode: always

telegram:
  bot:
    username: "${telegram_bot_username}"
    token: "${telegram_bot_token}"
    session:
      enable: true
      time-life:
        chat: 60
        user: 10

program-agent:
  charts:
    bot-message: true
  client:
    token: "${program_agent_client_token}"
    time-delay-send: 15000
    host: "https://wds-program-agent.ru/api/"
    myHost: "${program_agent_client_my_host}"

bot_owner_tg_id: 260113861